export const USSER_SIGN_UP_FLNAMES = 'USSER_SIGN_UP_FLNAMES';
export const USSER_SIGN_UP_DATE = 'USSER_SIGN_UP_DATE';
export const USSER_SIGN_UP_GENDER = 'USSER_SIGN_UP_GENDER';
export const USSER_SIGN_UP_MAILPHONE = 'USSER_SIGN_UP_MAILPHONE';
export const USSER_SIGN_UP_INTERESTED1 = 'USSER_SIGN_UP_INTERESTED1';
export const USSER_SIGN_UP_INTERESTED2 = 'USSER_SIGN_UP_INTERESTED2';
export const USSER_SIGN_UP_INTERESTED3 = 'USSER_SIGN_UP_INTERESTED3';
export const USSER_SIGN_UP_INTERESTEDTYPE = 'USSER_SIGN_UP_INTERESTEDTYPE';
export const USSER_SIGN_UP_INTERESTEDTYPE_INDIGENT =
  'USSER_SIGN_UP_INTERESTEDTYPE_INDIGENT';
export const USSER_SIGN_UP_PASSWORD = 'USSER_SIGN_UP_PASSWORD';
export const USSER_SIGN_UPLOCATION = 'USSER_SIGN_UPLOCATION';
export const USSER_SIGN_UP_LANGUEGE = 'USSER_SIGN_UP_LANGUEGE';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
