export const LOAD_APPEARS = 'appears/LOAD_APPEARS';
export const LOAD_APPEARS_ERROR = 'appears/LOAD_APPEARS_ERROR';
export const LOAD_APPEARS_SUCCESS = 'appears/LOAD_APPEARS_SUCCESS';
export const LOAD_APPEARS_INITIAL_SUCCESS =
  'appears/LOAD_APPEARS_INITIAL_SUCCESS';
export const LOAD_SPONSORS_INITIAL_SUCCESS =
  'appears/LOAD_SPONSORS_INITIAL_SUCCESS';
export const LOAD_SPONSORS_SUCCESS = 'appears/LOAD_SPONSORS_SUCCESS';
