export const LOAD_STORIES = 'stori/LOAD_STORIES';
export const SET_SINGLE_STORIES = 'stori/SET_SINGLE_STORIES';
export const LOAD_STORIES_ERROR = 'stori/LOAD_STORIES_ERROR';
export const LOAD_STORIES_SUCCESS = 'stori/LOAD_STORIES_SUCCESS';
export const LOAD_STORIES_INITIAL_SUCCESS =
  'stori/LOAD_STORIES_INITIAL_SUCCESS';
