export const LOAD_USERS = 'users/LOAD_USERS';
export const LOAD_USERS_SUCCESS = 'users/LOAD_USERS_SUCCESS';
export const LOAD_USERS_INITIAL_SUCCESS = 'users/LOAD_USERS_INITIAL_SUCCESS';
export const LOAD_USERS_ERROR = 'users/LOAD_USERS_ERROR';
