export const LOAD_MYPOSTS = 'myPosts/LOAD_MYPOSTS';
export const LOAD_MYPOSTS_ERROR = 'myPosts/LOAD_MYPOSTS_ERROR';
export const LOAD_MYPOSTS_SUCCESS = 'myPosts/LOAD_MYPOSTS_SUCCESS';
export const REMOVE_SINGLE_POST = 'myPosts/REMOVE_SINGLE_POST';
export const LOAD_MYPOSTS_INITIAL_SUCCESS =
  'myPosts/LOAD_MYPOSTS_INITIAL_SUCCESS';
export const LOAD_MYUSUBSCRIPTIONS_SUCCESS =
  'myPosts/LOAD_MYUSUBSCRIPTIONS_SUCCESS';
export const LOAD_MYUSUBSCRIPTIONS_INITIAL_SUCCESS =
  'myPosts/LOAD_MYUSUBSCRIPTIONS_INITIAL_SUCCESS';
export const LOAD_MYUSUBSCRIBERS_SUCCESS =
  'myPosts/LOAD_MYUSUBSCRIBERS_SUCCESS';
export const LOAD_MYUSUBSCRIBERS_INITIAL_SUCCESS =
  'myPosts/LOAD_MYUSUBSCRIBERS_INITIAL_SUCCESS';
